spring.application.name=backend
server.port=4040

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/chepu 
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
